# Generated by Django 4.2.13 on 2024-05-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='direction',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='identification',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(blank=True, default='', null=True, unique=True),
        ),
    ]
