# Generated by Django 4.2.13 on 2024-06-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_remove_parkingspot_spot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
