# Generated by Django 4.2.13 on 2024-06-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_ticket_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
    ]
