# Generated by Django 4.2.13 on 2024-06-25 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_brand_remove_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='parking.brand'),
            preserve_default=False,
        ),
    ]
